export const GET_ERRORS = 'GET_ERRORS';
export const RESET_ERRORS="RESET_ERRORS";


export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const UPLOAD_VIDEO ='UPLOAD_VIDEO'

